version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  DeployExtension: true
init:
- git config --global core.autocrlf true
install:
- nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.vsix'
